### ISSUE TITLE
Any plans to make this available on macOS?

### ISSUE THREAD

**Issue by aodrasa** [Adri6336/gpt-voice-conversation-chatbot#9]

**Comment by Adri6336** [comment]
Unfortunately there are no plans to make it available on MacOS. This is due to me not having access to a Mac for testing. I'm sorry for the inconvenience yo!

A previous user showed me an error related to this OS that points at the problem being mainly with the GUI of the main.py script. If this is the only issue, you should still be able to use gptcli.py to talk with the bot via text and take advantage of GPT-VCC's other functions. For the most part, the experience should be the same only that you won't be able to use your voice to speak with the bot

**Comment by dahifi** [comment]
This error is caused by a Mac OS quirk: 
pygame.error: NSWindow drag regions should only be invalidated on the Main Thread!

I'm trying to fix it, but so far no luck. I may keep banging on it.

**Comment by dahifi** [comment]
Fixed it in https://github.com/Adri6336/gpt-voice-conversation-chatbot/pull/20
